CREATE TABLE USER(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USERNAME TEXT NOT NULL,
  PASSWORD TEXT NOT NULL,
  EMAIL TEXT NOT NULL,
  PHONE TEXT NOT NULL,
  ADDRESS TEXT NOT NULL,
  CITY TEXT NOT NULL,
  STATE TEXT NOT NULL,
  ZIP TEXT NOT NULL,
  COUNTRY TEXT NOT NULL,
  DOB TEXT NOT NULL,
)